### ISSUE TITLE
Cannot compare images - Library not loaded, image not found

### ISSUE THREAD

**Issue by pashidlos** [dmtrKovalenko/odiff#41] opened 2021-06-05 14:30 UTC
not sure why it's not working

here is the repo to reproduce
https://github.com/pashidlos/image-compare-tryouts/blob/main/src/odiff.js

`node src/odiff.js`

```js
(node:24395) UnhandledPromiseRejectionWarning: Error: dyld: Library not loaded: _____________________________________________________________________________________/i/esy_libpng-635d6ecc/lib/libpng16.16.dylib
  Referenced from: /Users/pashidlos/work/image-compare-try/node_modules/odiff-bin/3/i/odiff-4d94fb12/bin/ODiffBin
  Reason: image not found
```

**Comment by eWert-Online** [comment] 2021-06-05 15:53
Which operating system are you using?

**Comment by pashidlos** [comment] 2021-06-05 16:34
@eWert-Online thanks for quick reply 
I'm on mac

**Comment by eWert-Online** [comment] 2021-06-05 18:00
It works on my mac, so it at least has nothing to do with your code ;)

The problem is, that odiff can't find libpng, which is a bit weird, because we provide it inside the node_modules.
It probably only works on my machine, because I have libpng installed globally.
I do have an idea where this might come from, but I will have to do some more investigation. 

If you need a quick fix for this, you might want to look into running this inside a Docker container.
It should work on an Ubuntu or Debian.

Another alternative would be, that you install libpng globally on your mac. This wouldn't be as nice for us though, as you couldn't verify, that the issue was indeed fixed, once we release a new version.

**Comment by eWert-Online** [comment] 2021-06-06 19:13
@dmtrKovalenko 
I looked into this issue a bit and I could reproduce it on another mac, by removing the globally installed libpng.

My first thought was, that camlimages didn't know about the provided libpng library, but this was not the case. 
Sadly it is a bit more difficult than that.

It seems like libpng includes hard coded paths to the esy store, which (as expected) it can't find when installed on another system. 
Normally you would fix this by enabling path rewriting, which we disabled because of its limitations (#29, #34).
The reasons behind the limitations are pretty well explained in this issue https://github.com/esy/esy/issues/711, if you wan't to look into this (it is quite interesting).

I currently see 4 possible ways to fix this: 

1. Find a way to lift the limitations of path rewriting in esy and re-enable it.
    _This would be the nicest, but probably most unlikely solution._
    
2. Remove the direct dependency to libpng and use something like https://github.com/rlepigre/ocaml-imagelib or camlimages for png io.
    _I use ocaml-imagelib in osnap and I don't have an issue with libpng. This would be the most straight forward way of fixing this, but would probably result in quite a slowdown._
    
3. Maybe a statically linked binary could also fix this.
    _I am not sure if this would fix it. Maybe you have some more insights.
    But I also don't know how well static linking works on a mac. Currently I only have experience with it on linux._

4. List libpng as an external requirement, like we are already doing with libjpg, libtiff and libxpm.
    _This could be a temporary workaround while we are working on a better solution_

What do you think?

**Comment by dmtrKovalenko** [comment] 2021-06-06 19:33
Hey, sorry to hear that this is a real issue :(

Here are my thoughts:

1. Really that should be the best one and we probably need to reach out esy for fixing our issue on windows
2. Camlimages still using libpng for loading but doing this 4 times slower than our direct implementation. 
3. Static linking doesn't allowed on MacOS at all
4. This will kill out us on windows. I spent literally dozens of hours to fix this because it is a hell on windows with external packages

**Comment by dmtrKovalenko** [comment] 2021-06-10 10:05
@eWert-Online do you know is it possible to build windows binary without `rewritePrefix` and other without it?

**Comment by eWert-Online** [comment] 2021-06-10 13:45
It isn't possible out of the box, no. 
I guess, you could always parse the package.json and replace the `rewritePrefix` in a ci step.

But I don't think this solves the problem. I didn't test it, but I think this problem currently occurs on all platforms (which haven't installed libpng globally).
Also enabling `rewritePrefix` for mac would break #34 again.

Btw: Did you see the conversation I had with Eduardo and Ulrik on Discord regarding this topic? He suggested maybe linking the static `libpng.a` would fix this problem. Do you have any experience with that?

**Comment by dmtrKovalenko** [comment] 2021-06-10 13:48
static linking doesn't allowed on MacOS as far I know https://stackoverflow.com/questions/844819/how-to-static-link-on-os-x 

And globally installing libpng is not an option because on windows it's a giant hell. You can not just take an install libpng, it is literally impossible. I am actually surprised that nobody asked about this.

**Comment by eWert-Online** [comment] 2021-06-10 13:57
Quote from Eduardo: 
> You cannot make a full static binary but if you add libpng.a to your cclib it just works

I don't know if that is correct though. I tried and it didn't work...but maybe I didn't do it right. Thats why I asked, if you had any experience with it. 🙂  

I didn't suggest installing libpng globally. 
I was just pointing out, that this problem probably also occurs on windows and linux. 🙂  
So enabling the rewritePrefix just for some of the os' would also only partially fix this problem on some os'

**Comment by EduardoRFS** [comment] 2021-06-10 16:04
@eWert-Online libpng.a should work, I think we do this at Revery, cc @bryphe but you can also use a different release mechanism, I think rewritePrefix is not supposed to work outside of esy

**Comment by EduardoRFS** [comment] 2021-06-10 16:48
Saw why it doesn't work, you actually can clean all the flags on discover.ml and it will still work, because camlimages is adding `-lpng16` and that will always link with `libpng16.so`. And it's even linking against the OS libpng on my system

```sh
libpng16.so.16 => /usr/lib/libpng16.so.16
```

There is a couple of ways around this, vendor camlimages and fix it, but also emitting a complete object and linking it by hand into an executable will work.

Also libpng is not built with -fPIC and there is also `-ljpeg` https://github.com/EduardoRFS/esy-libpng/commit/b326ae3e63df820ad0fcf5ac02ad0d70ca9ef24f 

Both can be linked statically you just need to remove `-lpng16` and `-ljpeg` from all occurrences or you can add the `.a` before the `-lpng16` and remove using patchelf

**Comment by eWert-Online** [comment] 2021-06-10 16:49
@EduardoRFS
Yes, I found [this](https://github.com/revery-ui/revery/blob/4337e2c940abba3b146e55213f32f71bd9048908/packages/reason-sdl2/src/config/discover.re#L136) which I based my failed attempts on. But as I said, maybe I also did something wrong. I am not that experienced with c compilers.

`rewritePrefix` is documented under "Building npm Releases" in the esy documentation, so my assumption always was, that it should work. But maybe it is better to discuss this in https://github.com/esy/esy/issues/1322 🙂

**Closed** 2021-06-17 17:09 UTC

**Comment by pashidlos** [comment] 2021-06-18 07:25
@dmtrKovalenko @eWert-Online thanks for quick fix 
unfortunately the problem still remains for me :(
error changed a bit 
```
(base) pashidlos@Pavels-MBP image-compare-try % node src/odiff.js
(node:44410) UnhandledPromiseRejectionWarning: Error: dyld: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: /Users/pashidlos/work/image-compare-try/node_modules/odiff-bin/3/i/odiff-bc6962b3/bin/ODiffBin
  Reason: image not found

    at ChildProcess.<anonymous> (/Users/pashidlos/work/image-compare-try/node_modules/odiff-bin/odiff.js:134:13)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

I updated the version to `2.4.0` in repo 
https://github.com/pashidlos/image-compare-tryouts/blob/main/src/odiff.js

**Comment by dmtrKovalenko** [comment] 2021-06-18 07:26
Can you please verify that you don't have or have libtiff installed?

**Comment by dmtrKovalenko** [comment] 2021-06-18 07:27
This usually mean that you have lib tiff link in the package config but the file itself doesn't exist in file system

**Comment by pashidlos** [comment] 2021-06-18 07:37
> Can you please verify that you don't have or have libtiff installed?

I didn't install it manually
`libtiff` folder does not exist in `usr/local/opt/ `
or how should I check it?
